pipeline {
    agent any
    environment {
        IMAGE_NAME = "talhafayyaz/app-a:${env.BUILD_ID}"
        COMPOSE_DIR = "app-a"
    }
    stages {
        stage('Build') {
            steps {
                sh "cd ${COMPOSE_DIR} && docker build -t ${IMAGE_NAME} ."
            }
        }
        stage('Deploy') {
            steps {
                // Update the docker-compose file image version on remote server
                sh "sed -i 's|image:.*|image: ${IMAGE_NAME}|g' ${COMPOSE_DIR}/docker-compose.yml"
                
                // Ensure .env file exists and is updated
                sh "cd ${COMPOSE_DIR} && cp -f .env.example .env || true"
                
                // Pull and recreate ONLY this specific service with zero downtime (if using Traefik)
                sh "cd ${COMPOSE_DIR} && docker-compose up -d"
            }
        }
        stage('Clean') {
            steps {
                sh "docker system prune -f"
            }
        }
    }
}
